# Generated by Django 2.0 on 2020-04-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('shipment_id', models.PositiveIntegerField()),
                ('shipment_date', models.DateTimeField()),
                ('transport_id', models.PositiveIntegerField()),
                ('basic_info', models.TextField()),
                ('complete_info', models.TextField()),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
            },
        ),
    ]
