# Generated by Django 2.0 on 2020-04-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='fulfilment_method',
            field=models.CharField(choices=[('FBR', 'FBR'), ('FBB', 'FBB')], default='FBR', max_length=10),
            preserve_default=False,
        ),
    ]
