# Generated by Django 2.0 on 2020-04-25 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_shipment_fulfilment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shop_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.ShopDetail'),
            preserve_default=False,
        ),
    ]
